import 'package:http/http.dart' as http;
import '../generated/gtfs-realtime.pb.dart';

/// Parses Malaysia's official GTFS-Realtime feed for rapid-bus-kl vehicle
/// positions. See README "Known limitations" — rapid-rail-kl (trains) has
/// no equivalent realtime feed, so there is no TrainRealtimeService.
///
/// NOTE: this file imports '../generated/gtfs-realtime.pb.dart', which you
/// generate yourself locally via protoc (see the setup steps we walked
/// through). That generated file is NOT included in this zip — see the
/// README warning at the top of this project.
class VehiclePositionInfo {
  final String vehicleId;
  final String? routeId;
  final double latitude;
  final double longitude;

  VehiclePositionInfo({
    required this.vehicleId,
    required this.routeId,
    required this.latitude,
    required this.longitude,
  });
}

class BusRealtimeService {
  // Prasarana's rapid-bus-kl vehicle position feed. Note: rapid-rail-kl
  // (trains, e.g. Kelana Jaya Line) has no equivalent realtime feed at
  // all — confirmed in the official docs — so there is no
  // TrainRealtimeService; trains stay schedule-only (see transit_api_service.dart).
  static const _url =
      'https://api.data.gov.my/gtfs-realtime/vehicle-position/prasarana?category=rapid-bus-kl';

  Future<List<VehiclePositionInfo>> fetchVehiclePositions() async {
    final response = await http.get(Uri.parse(_url));

    if (response.statusCode != 200) {
      throw Exception('Failed to load vehicle positions: ${response.statusCode}');
    }

    // Protobuf equivalent of jsonDecode(response.body) — FeedMessage.fromBuffer()
    // parses the raw bytes using the schema generated by protoc.
    final feed = FeedMessage.fromBuffer(response.bodyBytes);

    // Keep only entities that actually have a live GPS position attached —
    // the feed can include vehicles with other data but no position.
    return feed.entity
        .where((e) => e.hasVehicle() && e.vehicle.hasPosition())
        .map((e) => VehiclePositionInfo(
              vehicleId: e.vehicle.vehicle.id,
              // routeId here is the raw internal GTFS ID — see
              // route_lookup_service.dart for how map_screen.dart turns
              // this into a human-readable bus number like "300".
              routeId: e.vehicle.hasTrip() ? e.vehicle.trip.routeId : null,
              latitude: e.vehicle.position.latitude,
              longitude: e.vehicle.position.longitude,
            ))
        .toList();
  }
}
